# 데이터베이스 설정
server:
  port : 8080


spring:
  datasource:
    url: jdbc:mysql://52.78.243.24:3306/myboard?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: boardroot
    password: 2456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect



# 페이지네이션 설정
app:
  pagination:
    default-page-size: 10   # 한 페이지에 표시할 게시글 수

# Spring Security 설정
security:
  enabled: true             # 권한 관리 활성화
  roles:
    admin: ADMIN
    user: USER
  permissions:
    create: [ADMIN, USER]
    read: [ADMIN, USER, GUEST]   # 모두에게 읽기 권한 부여
    update: [ADMIN, USER]
    delete: [ADMIN]
